# Generated by Django 3.2.9 on 2021-11-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharekitapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
