# Generated by Django 3.2.9 on 2021-11-16 03:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharekitapp', '0003_auto_20211113_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demat',
            name='boid',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='invalid_boid', message='Invalid BOID', regex='^1301\\d{12}$')]),
        ),
    ]
